name: CD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permisos a gradlew
        run: chmod +x gradlew

      - name: Ejecutar pruebas
        run: ./gradlew test

      - name: Construir proyecto
        run: ./gradlew clean build

      - name: Publicar artefacto JAR
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar